# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_test
        command: --default-authentication-plugin=mysql_native_password
        #        working_dir: /application
        volumes:
            - '.:/var/lib/test'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=amit
            - MYSQL_DATABASE=dummy
            - MYSQL_USER=amit
            - MYSQL_PASSWORD=pass
        ports:
            - "3306:3306"
    website:
        container_name: php72_test
        build:
            context: ./
        volumes:
            - '.:/var/www/html'
        ports:
            - 8000:80
        depends_on:
            - mysql
